"""modelagem inicial da conferência pré-faturamento

Revision ID: e5c3d5af888e
Revises:
Create Date: 2026-09-02 19:55:05.918449

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e5c3d5af888e"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "operadoras",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("nome", sa.String(), nullable=False),
        sa.Column("codigo", sa.String(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("codigo"),
    )
    op.create_table(
        "pacientes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("nome", sa.String(), nullable=False),
        sa.Column("operadora_id", sa.UUID(), nullable=False),
        sa.Column("data_vencimento_pad", sa.Date(), nullable=True),
        sa.Column("status_pad", sa.String(), nullable=True),
        sa.Column("modalidade", sa.Enum("AD", "ID", name="paciente_modalidade"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["operadora_id"],
            ["operadoras.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "regras",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("operadora_id", sa.UUID(), nullable=False),
        sa.Column("campo", sa.String(), nullable=False),
        sa.Column("condicao", sa.String(), nullable=False),
        sa.Column("acao", sa.String(), nullable=False),
        sa.Column("motivo_glosa", sa.String(), nullable=False),
        sa.Column("ativo", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["operadora_id"],
            ["operadoras.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "documentos",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("paciente_id", sa.UUID(), nullable=True),
        sa.Column("operadora_id", sa.UUID(), nullable=True),
        sa.Column(
            "tipo",
            sa.Enum("evolucao", "ficha_visita", "boletim", "matmed", name="documento_tipo"),
            nullable=False,
        ),
        sa.Column("arquivo_url", sa.String(), nullable=False),
        sa.Column("competencia", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "processando",
                "aprovado",
                "problema",
                "incompleto",
                "em_correcao",
                "resolvido",
                "liberado",
                name="documento_status",
            ),
            nullable=False,
        ),
        sa.Column("pagina", sa.Integer(), nullable=True),
        sa.Column("idempotency_key", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["operadora_id"],
            ["operadoras.id"],
        ),
        sa.ForeignKeyConstraint(
            ["paciente_id"],
            ["pacientes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(op.f("ix_documentos_competencia"), "documentos", ["competencia"], unique=False)
    op.create_index(
        "ix_documentos_paciente_id_competencia",
        "documentos",
        ["paciente_id", "competencia"],
        unique=False,
    )
    op.create_index(op.f("ix_documentos_status"), "documentos", ["status"], unique=False)
    op.create_table(
        "extracoes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("documento_id", sa.UUID(), nullable=False),
        sa.Column("campos_extraidos", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("confianca", sa.Float(), nullable=False),
        sa.Column("confianca_por_campo", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("raw_response_ref", sa.Text(), nullable=True),
        sa.Column("modelo", sa.Text(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["documento_id"],
            ["documentos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "log_conferencia",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("documento_id", sa.UUID(), nullable=False),
        sa.Column("acao", sa.String(), nullable=False),
        sa.Column("usuario", sa.String(), nullable=False),
        sa.Column("detalhe", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["documento_id"],
            ["documentos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pendencias",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("documento_id", sa.UUID(), nullable=False),
        sa.Column("tipo_problema", sa.String(), nullable=False),
        sa.Column("descricao", sa.String(), nullable=False),
        sa.Column("responsavel", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("aberta", "em_correcao", "resolvida", name="pendencia_status"),
            nullable=False,
        ),
        sa.Column("deadline", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["documento_id"],
            ["documentos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_pendencias_deadline", "pendencias", ["deadline"], unique=False)
    op.create_index(op.f("ix_pendencias_status"), "pendencias", ["status"], unique=False)
    op.create_table(
        "validacoes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("documento_id", sa.UUID(), nullable=False),
        sa.Column("regra_id", sa.UUID(), nullable=False),
        sa.Column(
            "resultado",
            sa.Enum("aprovado", "reprovado", name="validacao_resultado"),
            nullable=False,
        ),
        sa.Column("detalhe", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["documento_id"],
            ["documentos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["regra_id"],
            ["regras.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("validacoes")
    op.drop_index(op.f("ix_pendencias_status"), table_name="pendencias")
    op.drop_index("ix_pendencias_deadline", table_name="pendencias")
    op.drop_table("pendencias")
    op.drop_table("log_conferencia")
    op.drop_table("extracoes")
    op.drop_index(op.f("ix_documentos_status"), table_name="documentos")
    op.drop_index("ix_documentos_paciente_id_competencia", table_name="documentos")
    op.drop_index(op.f("ix_documentos_competencia"), table_name="documentos")
    op.drop_table("documentos")
    op.drop_table("regras")
    op.drop_table("pacientes")
    op.drop_table("operadoras")
    # ### end Alembic commands ###

    # Autogenerate não dropa tipos enum nativos do Postgres — feito à mão
    # aqui pra não deixar tipo órfão depois do downgrade das tabelas que os
    # usam (ver critério de aceite #2 do handoff da Trilha A).
    bind = op.get_bind()
    postgresql.ENUM(name="documento_status").drop(bind, checkfirst=True)
    postgresql.ENUM(name="documento_tipo").drop(bind, checkfirst=True)
    postgresql.ENUM(name="paciente_modalidade").drop(bind, checkfirst=True)
    postgresql.ENUM(name="pendencia_status").drop(bind, checkfirst=True)
    postgresql.ENUM(name="validacao_resultado").drop(bind, checkfirst=True)
